export const ADD_INGREDIENT_TO_ORDER = 'ADD_INGREDIENT_TO_ORDER';
export const REMOVE_INGREDIENT_FROM_ORDER = 'REMOVE_INGREDIENT_FROM_ORDER';
export const RESET_CURRENT_ORDER = 'RESET_CURRENT_ORDER';
export const MOVE_INGREDIENTS = 'MOVE_INGREDIENTS';
