// App action types
export const SET_ERROR: 'SET_ERROR' = 'SET_ERROR';
export const FETCH_INGREDIENTS_REQUEST: 'FETCH_INGREDIENTS_REQUEST' = 'FETCH_INGREDIENTS_REQUEST';
export const FETCH_INGREDIENTS_SUCCESS: 'FETCH_INGREDIENTS_SUCCESS' = 'FETCH_INGREDIENTS_SUCCESS';
export const FETCH_INGREDIENTS_ERROR: 'FETCH_INGREDIENTS_ERROR' = 'FETCH_INGREDIENTS_ERROR';
export const RESET_ERROR: 'RESET_ERROR' = 'RESET_ERROR';

// Burger constructor action types
export const ADD_INGREDIENT_TO_ORDER: 'ADD_INGREDIENT_TO_ORDER' = 'ADD_INGREDIENT_TO_ORDER';
export const REMOVE_INGREDIENT_FROM_ORDER: 'REMOVE_INGREDIENT_FROM_ORDER' = 'REMOVE_INGREDIENT_FROM_ORDER';
export const RESET_CURRENT_ORDER: 'RESET_CURRENT_ORDER' = 'RESET_CURRENT_ORDER';
export const MOVE_INGREDIENTS: 'MOVE_INGREDIENTS' = 'MOVE_INGREDIENTS';
export const SET_NUMBER: 'SET_NUMBER' = 'SET_NUMBER';

// Detail modal action types
export const TOGGLE_MODAL: 'TOGGLE_MODAL' = 'TOGGLE_MODAL';
export const SET_INGREDIENT: 'SET_INGREDIENT' = 'SET_INGREDIENT';
export const RESET_INGREDIENT: 'RESET_INGREDIENT' = 'RESET_INGREDIENT';

// Order action types
export const CREATE_ORDER_REQUEST: 'CREATE_ORDER_REQUEST' = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS' = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_ERROR: 'CREATE_ORDER_ERROR' = 'CREATE_ORDER_ERROR';

// Order history types
export const SET_ORDER_HISTORY: 'SET_ORDER_HISTORY' = 'SET_ORDER_HISTORY';
export const SET_ORDER_SUCCESS: 'SET_ORDER_SUCCESS' = 'SET_ORDER_SUCCESS';
export const SET_ORDER_REQUEST: 'SET_ORDER_REQUEST' = 'SET_ORDER_REQUEST';
export const SET_ORDER_FAILED: 'SET_ORDER_FAILED' = 'SET_ORDER_FAILED';

// Reset password action types
export const PASSWORD_RESET_REQUEST: 'PASSWORD_RESET_REQUEST' = 'PASSWORD_RESET_REQUEST';
export const PASSWORD_RESET_SUCCESS: 'PASSWORD_RESET_SUCCESS' = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_ERROR: 'PASSWORD_RESET_ERROR' = 'PASSWORD_RESET_ERROR';
export const CONFIRM_PASSWORD_RESET_REQUEST: 'CONFIRM_PASSWORD_RESET_REQUEST' = 'CONFIRM_PASSWORD_RESET_REQUEST';
export const CONFIRM_PASSWORD_RESET_SUCCESS: 'CONFIRM_PASSWORD_RESET_SUCCESS' = 'CONFIRM_PASSWORD_RESET_SUCCESS';
export const CONFIRM_PASSWORD_RESET_ERROR: 'CONFIRM_PASSWORD_RESET_ERROR' = 'CONFIRM_PASSWORD_RESET_ERROR';

// Socket action types
export const SOCKET_CREATE: 'SOCKET_CREATE' = 'SOCKET_CREATE';
export const SOCKET_OPEN: 'SOCKET_OPEN' = 'SOCKET_OPEN';
export const SOCKET_CLOSE: 'SOCKET_CLOSE' = 'SOCKET_CLOSE';
export const SOCKET_ERROR: 'SOCKET_ERROR' = 'SOCKET_ERROR';
export const SOCKET_DATA: 'SOCKET_DATA' = 'SOCKET_DATA';

// User action types
export const FETCH_USER_REQUEST: 'FETCH_USER_REQUEST' = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS' = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR: 'FETCH_USER_ERROR' = 'FETCH_USER_ERROR';
export const UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST' = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS' = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR: 'UPDATE_USER_ERROR' = 'UPDATE_USER_ERROR';
export const LOGIN_REQUEST: 'LOGIN_REQUEST' = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS: 'LOGIN_SUCCESS' = 'LOGIN_SUCCESS';
export const LOGIN_ERROR: 'LOGIN_ERROR' = 'LOGIN_ERROR';
export const LOGOUT_REQUEST: 'LOGOUT_REQUEST' = 'LOGOUT_REQUEST';
export const LOGOUT_ERROR: 'LOGOUT_ERROR' = 'LOGOUT_ERROR';
export const LOGOUT_SUCCESS: 'LOGOUT_SUCCESS' = 'LOGOUT_SUCCESS';
export const SIGNUP_REQUEST: 'SIGNUP_REQUEST' = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS: 'SIGNUP_SUCCESS' = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR: 'SIGNUP_ERROR' = 'SIGNUP_ERROR';
